development:
  adapter: postgresql
  encoding: unicode
  database: foodplans_development
  pool: 5
  username: bob
  password: bob

test:
  adapter: postgresql
  encoding: unicode
  database: foodplans_test
  pool: 5
  username: bob
  password: bob

production:
  adapter: postgresql
  encoding: unicode
  database: foodplans_test
  pool: 5
  username: bob
  password: bob


